title: "neople-openapi-types"
description: "네오플 Open API를 위한 포괄적인 TypeScript 타입 정의 라이브러리"

# GitHub Pages 설정
theme: minima
markdown: kramdown
highlighter: rouge

# 플러그인
plugins:
  - jekyll-sitemap
  - jekyll-feed

# 네비게이션
header_pages:
  - index.md

# 소셜 링크
github_username: crowrish
repository: "crowrish/neople-openapi-types"

# 기본 설정
show_excerpts: true
permalink: /:categories/:title/

# 제외할 파일들
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tsconfig.json
  - api-extractor.json
  - tsdoc.json